### ISSUE TITLE
angularjs error

### ISSUE THREAD

**Issue by cosenal** [owncloud-archive/news-mobile#18]
Again, app from the marketplace

![2014-01-25-12-56-49](https://f.cloud.github.com/assets/1048336/2001583/e1aca012-85b8-11e3-96ba-26a915f2fd34.png)

**Comment by ilijalazarevic** [comment]
Ok, I have replicated this bug. The problem is with link missing from link field in oc_news_feeds table.

**Comment by ilijalazarevic** [comment]
This is hopefully fixed in add662d commit.

**Comment by ilijalazarevic** [comment]
cc @Raydiation

**Comment by cosenal** [comment]
I wonder if we should allow empty link fields in the db anyway. They might cause other issues.

**Comment by BernhardPosselt** [comment]
@icewind1991 just submitted a patch for that some days ago

**Comment by cosenal** [comment]
That PR doesnt fix this. Here the issue is about the feed link itself being missing

**Comment by BernhardPosselt** [comment]
Ah it was for an item only :)
